name: eco_tracker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^2.10.0
  firebase_auth: ^6.5.0
  cloud_firestore: ^5.7.0
  firebase_analytics: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/vector_68_x2.svg
    - assets/vectors/vector_59_x2.svg
    - assets/vectors/vector_28_x2.svg
    - assets/vectors/vector_36_x2.svg
    - assets/vectors/vector_41_x2.svg
    - assets/group_15_x2.svg
    - assets/vectors/vector_35_x2.svg
    - assets/vectors/vector_57_x2.svg
    - assets/vectors/vector_x2.svg
    - assets/vectors/network_signal_light_6_x2.svg
    - assets/vectors/vector_20_x2.svg
    - assets/vectors/wi_fi_signal_light_6_x2.svg
    - assets/vectors/vector_6_x2.svg
    - assets/vectors/battery_light_7_x2.svg
    - assets/vectors/image_x2.svg
    - assets/vectors/vector_30_x2.svg
    - assets/vectors/vector_16_x2.svg
    - assets/vectors/container_1_x2.svg
    - assets/vectors/vector_44_x2.svg
    - assets/vectors/vector_54_x2.svg
    - assets/vectors/vector_49_x2.svg
    - assets/vectors/container_5_x2.svg
    - assets/vectors/wi_fi_signal_light_12_x2.svg
    - assets/vectors/image_16_x2.svg
    - assets/vectors/network_signal_light_8_x2.svg
    - assets/vectors/battery_light_5_x2.svg
    - assets/images/ellipse_21.jpeg
    - assets/vectors/ellipse_3_x2.svg
    - assets/vectors/wi_fi_signal_light_7_x2.svg
    - assets/vectors/vector_13_x2.svg
    - assets/vectors/battery_light_8_x2.svg
    - assets/vectors/image_15_x2.svg
    - assets/vectors/container_3_x2.svg
    - assets/vectors/vector_61_x2.svg
    - assets/vectors/network_signal_light_4_x2.svg
    - assets/vectors/vector_27_x2.svg
    - assets/vectors/vector_72_x2.svg
    - assets/vectors/network_signal_light_13_x2.svg
    - assets/vectors/wi_fi_signal_light_11_x2.svg
    - assets/vectors/image_3_x2.svg
    - assets/vectors/vector_32_x2.svg
    - assets/vectors/battery_light_x2.svg
    - assets/vectors/vector_12_x2.svg
    - assets/vectors/vector_55_x2.svg
    - assets/vectors/vector_24_x2.svg
    - assets/vectors/vector_19_x2.svg
    - assets/vectors/vector_69_x2.svg
    - assets/vectors/image_14_x2.svg
    - assets/vectors/vector_43_x2.svg
    - assets/vectors/vector_31_x2.svg
    - assets/vectors/wi_fi_signal_light_4_x2.svg
    - assets/vectors/battery_light_1_x2.svg
    - assets/vectors/vector_42_x2.svg
    - assets/vectors/vector_48_x2.svg
    - assets/vectors/vector_50_x2.svg
    - assets/vectors/vector_56_x2.svg
    - assets/vectors/vector_39_x2.svg
    - assets/vectors/vector_17_x2.svg
    - assets/vectors/network_signal_light_x2.svg
    - assets/vectors/vector_46_x2.svg
    - assets/vectors/vector_38_x2.svg
    - assets/vectors/vector_63_x2.svg
    - assets/vectors/network_signal_light_10_x2.svg
    - assets/vectors/battery_light_11_x2.svg
    - assets/vectors/image_2_x2.svg
    - assets/vectors/wi_fi_signal_light_8_x2.svg
    - assets/vectors/vector_29_x2.svg
    - assets/vectors/vector_66_x2.svg
    - assets/vectors/vector_53_x2.svg
    - assets/vectors/vector_64_x2.svg
    - assets/images/ellipse_21.jpeg
    - assets/vectors/vector_18_x2.svg
    - assets/vectors/vector_45_x2.svg
    - assets/vectors/container_2_x2.svg
    - assets/vectors/image_12_x2.svg
    - assets/vectors/vector_11_x2.svg
    - assets/vectors/wi_fi_signal_light_5_x2.svg
    - assets/vectors/network_signal_light_11_x2.svg
    - assets/vectors/battery_light_6_x2.svg
    - assets/images/ellipse_9.jpeg
    - assets/images/ellipse_2.jpeg
    - assets/images/ellipse_6.jpeg
    - assets/images/ellipse_5.jpeg
    - assets/images/ellipse_8.jpeg
    - assets/vectors/shape_8_x2.svg
    - assets/vectors/shape_13_x2.svg
    - assets/vectors/shape_9_x2.svg
    - assets/vectors/shape_2_x2.svg
    - assets/vectors/shape_14_x2.svg
    - assets/vectors/shape_3_x2.svg
    - assets/vectors/wifi_x2.svg
    - assets/vectors/shape_1_x2.svg
    - assets/vectors/shape_15_x2.svg
    - assets/vectors/group_1_x2.svg
    - assets/vectors/shape_10_x2.svg
    - assets/vectors/battery_x2.svg
    - assets/vectors/shape_7_x2.svg
    - assets/vectors/shape_11_x2.svg
    - assets/vectors/shape_12_x2.svg
    - assets/images/rectangle_40.jpeg
    - assets/images/rectangle_41.jpeg
    - assets/vectors/vector_40_x2.svg
    - assets/vectors/image_5_x2.svg
    - assets/vectors/vector_67_x2.svg
    - assets/vectors/battery_light_10_x2.svg
    - assets/vectors/wi_fi_signal_light_14_x2.svg
    - assets/vectors/vector_10_x2.svg
    - assets/vectors/vector_3_x2.svg
    - assets/vectors/vector_2_x2.svg
    - assets/vectors/network_signal_light_1_x2.svg
    - assets/vectors/vector_26_x2.svg
    - assets/vectors/vector_37_x2.svg
    - assets/vectors/vector_74_x2.svg
    - assets/vectors/primecar_x2.svg
    - assets/vectors/network_signal_light_12_x2.svg
    - assets/vectors/vector_25_x2.svg
    - assets/vectors/battery_light_2_x2.svg
    - assets/vectors/wi_fi_signal_light_x2.svg
    - assets/vectors/vector_47_x2.svg
    - assets/vectors/vector_73_x2.svg
    - assets/vectors/vector_34_x2.svg
    - assets/vectors/vector_33_x2.svg
    - assets/vectors/image_13_x2.svg
    - assets/vectors/vector_70_x2.svg
    - assets/images/rectangle_561.jpeg
    - assets/images/rectangle_41.jpeg
    - assets/images/rectangle_40.jpeg
    - assets/images/rectangle_33.jpeg
    - assets/vectors/vector_14_x2.svg
    - assets/vectors/vector_62_x2.svg
    - assets/vectors/vector_21_x2.svg
    - assets/vectors/vector_23_x2.svg
    - assets/vectors/vector_71_x2.svg
    - assets/vectors/vector_5_x2.svg
    - assets/images/rectangle_561.jpeg
    - assets/images/rectangle_33.jpeg
    - assets/images/rectangle_563.jpeg
    - assets/images/rectangle_56.jpeg
    - assets/images/rectangle_562.jpeg
    - assets/vectors/vector_1_x2.svg
    - assets/vectors/vector_7_x2.svg
    - assets/vectors/vector_51_x2.svg
    - assets/vectors/image_7_x2.svg
    - assets/vectors/wi_fi_signal_light_9_x2.svg
    - assets/vectors/vector_52_x2.svg
    - assets/vectors/network_signal_light_5_x2.svg
    - assets/vectors
